version: '3.9'
services:
  scalabel:
    image: scalabel/www
    container_name: scalabel
    # stdin_open: true
    # tty: true
    ports:
      - 8686:8686
      - 6379:6379
    volumes:
      - ./local_config.yml:/opt/scalabel/local-data/scalabel/config.yml # config file
      - ./local:/opt/scalabel/local-data/local
      - $HOME/example/imgs_00:/opt/scalabel/local-data/items/imgs_00 # 文件挂载
    command:
      - /bin/bash
      - -c
      - |
        node app/dist/main.js --config /opt/scalabel/local-data/scalabel/config.yml \
        --max-old-space-size=8192
